### ISSUE TITLE
About Fine-tuning

### ISSUE THREAD

**Issue by fukuzawa-e** [tingyu215/VACNIC#1]
where is the source of "/CODEDIR/train_mmbart_enc_self_face_name_ids_retrieve_crossattn_bart_guide_match.py" for fine-training ?

**Comment by tingyu215** [comment]
Hi, it's the train_mmbart_enc_self_face_name_ids_retrieve_crossattn_bart_guide_match.py file in this repo. You can replace CODEDIR with the dir where you store the codebase, or just delete CODEDIR as train_mmbart_enc_self_face_name_ids_retrieve_crossattn_bart_guide_match.py and run_full_train.sh are under the same dir.

**Comment by fukuzawa-e** [comment]
Thank you so much. I have found it.
